const ACTION_TYPES = {
    FETCH_MOVIES_REQUEST:  'FETCH_MOVIES_REQUEST',
    FETCH_MOVIES_SUCCESS:  'FETCH_MOVIES_RESPONSE',
    FETCH_MOVIES_FAILURE:  'FETCH_MOVIES_FAILURE',


}
export default ACTION_TYPES;